# SPDX-License-Identifier: AGPL-3.0-or-later
FROM fluxer-dev-workspace:latest

ARG HANDOFF_IMAGE_VERSION=v1
ENV HANDOFF_IMAGE_VERSION=${HANDOFF_IMAGE_VERSION}

USER vscode
WORKDIR /workspaces/fluxer/fluxer_gateway

COPY --chown=vscode:vscode _build/test/lib/fluxer_gateway/ebin /workspaces/fluxer/fluxer_gateway/_build/test/lib/fluxer_gateway/ebin
