# SPDX-License-Identifier: AGPL-3.0-or-later

svc:
  shard:
    replicas: 4
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        memory: 1Gi
  router:
    replicas: 3
    resources:
      requests:
        cpu: 250m
        memory: 128Mi
      limits:
        memory: 256Mi
  cache:
    maxEntries: 500000
    ttlMs: 30000
